# Generated by Django 5.1.4 on 2025-01-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_answer_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.variant'),
        ),
    ]
